name: bot-prison
version: @version@-@apiversion@
description: Sends certain players to a prison dimention and prevents them from moving or taking any non-chat/command action
authors: [Amelorate]
website: https://github.com/Ameliorate/BotPrison/tree/master

main: org.ame.botprison.Main

commands:
  bpreload:
    description: Reload the BotPrison config.
    usage: /bpreload
